### ISSUE TITLE
Questions about dataset

### ISSUE THREAD

**Issue by junhyukso** [Maclory/Deep-Iterative-Collaboration#14] opened 2020-08-14 02:28 UTC
Hi,thank you very much for your sharing the code! 
I have some question about why Face SR is dataset depedent.

I tried using the Helen model on the CelebA dataset, but the results were not good. 
Also, I tried using Helen model and CelebA model to some real-world small faces, but results were bad.

Is this model need some fine-tuning to use in other dataset?

**Comment by Maclory** [comment] 2020-08-15 02:00
Thank you for your interest in our work.  

On the one hand, in my opinion, the poor performance of the Helen model on CelebA may be caused by the overfitting problem, since Helen is a relatively small dataset. 
On the other hand, there exists discrepancy between the training data and real-world data. I think our method indeed needs improvement on the capacity of transferring to new data. Actually, this is also an interesting and valuable research direction.

**Closed as completed** 2020-08-17 02:33 UTC
